### ISSUE TITLE
Test predictions length not exceeding 5

### ISSUE THREAD

**Issue by devarshi16** [GabrielDornelles/TorchNN-OCR#11]
I am trying to train a number plate recognition model. The lengths can be upto 13 characters long. But the test predictions that I see after each epoch has at max 5 characters in it. What am I missing?

config/config.yaml:
```
defaults:
  - override hydra/job_logging: custom
  
processing:
  device: cuda
  image_width: 200
  image_height: 60 
  
training:
  lr: 3e-4
  batch_size: 1
  num_workers: 10
  num_epochs: 20
  device: "cuda"

bools:
  DISPLAY_ONLY_WRONG_PREDICTIONS: false
  VIEW_INFERENCE_WHILE_TRAINING: true
  SAVE_CHECKPOINTS: false

paths:
  dataset_dir: ./dataset
  save_model_as: ./logs/crnn.pth

model:
  use_attention: true 
  use_ctc: true
  gray_scale: false
  dims: 256
```
Also, Accuracy and Best Accuracy columns are always 0.0 for some reason.

**Note:** if I keep anything other than batch size 1 I am gettig the error  `"Trying to resize storage that is not resizable" when calling pin_memory() on some zero-dimensional tensors` although it looks like it might be a torch version issue [Similar issue in ultralytics ](https://github.com/pytorch/pytorch/issues/15770)

Will appreciate any help thank you.
